{{- if .Values.config.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "application.labels" . | nindent 4 }}
    component: postgres
type: Opaque
data:
  user: {{ include "postgres.username" . | b64enc }}
  password: {{ include "postgres.password" . | b64enc }}
{{- end }}