{{- if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    {{- include "application.labels" . | nindent 4 }}
    component: proxy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 60 # warm up the cache before deleting old pods
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy
        component: proxy
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-proxy
      containers:
        - name: proxy
          image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
{{- end }} 