{{- if .Values.proxy.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-proxy
  annotations:
    cert-manager.io/issuer: {{ .Release.Name }}-proxy
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  labels:
    {{- include "application.labels" . | nindent 4 }}
    component: proxy
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.proxy.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-proxy
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.proxy.ingress.host }}
      secretName: {{ .Release.Name }}-proxy-letsencrypt-tls
{{- end }} 