{{- if and .Values.proxy.enabled .Values.proxy.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    {{- include "application.labels" . | nindent 4 }}
    component: proxy
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pavlo.tsisar@desynclabs.com
    privateKeySecretRef:
      name: {{ .Release.Name }}-proxy-letsencrypt-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }} 