name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Release Indexer
        run: make release COMPONENT=indexer

      - name: Release Subgraph
        run: make release COMPONENT=subgraph

      - name: Sync Argo CD and wait for completion
        run: |
          echo "Syncing Argo CD application..."
#          MAX_RETRIES=3
#          RETRY_DELAY=10
#          RETRIES=0
#
#          until [ $RETRIES -ge $MAX_RETRIES ]
#          do
#            docker run --rm \
#              -e ARGOCD_AUTH_TOKEN=${{ secrets.ARGOCD_AUTH_TOKEN }} \
#              argoproj/argocd:v2.6.15 \
#              /bin/sh -c \
#              "argocd app set ${{ vars.ARGOCD_APP_NAME }} \
#              --server ${{ secrets.ARGOCD_API_URL }} \
#              --grpc-web \
#              --parameter image.tag=${{ github.sha }} && \
#              argocd app wait ${{ vars.ARGOCD_APP_NAME }} \
#              --server ${{ secrets.ARGOCD_API_URL }} \
#              --grpc-web \
#              --operation && \
#              argocd app sync ${{ vars.ARGOCD_APP_NAME }} \
#              --server ${{ secrets.ARGOCD_API_URL }} \
#              --grpc-web \
#              --timeout 180" && break
#
#            RETRIES=$((RETRIES+1))
#            echo "Retrying... ($RETRIES/$MAX_RETRIES)"
#            sleep $RETRY_DELAY
#          done
#
#          if [ $RETRIES -eq $MAX_RETRIES ]; then
#            echo "Failed to sync after $MAX_RETRIES attempts"
#            exit 1
#          fi